"""Audit evidence and deterministic tamper-evidence concepts."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any


@dataclass(frozen=True, slots=True)
class AuditEvidence:
    """One auditable reference event."""

    evidence_id: str
    event_type: str
    actor: str
    actor_type: str
    timestamp: datetime
    correlation_id: str
    source_component: str
    action: str
    outcome: str
    provenance: str
    approval_reference: str | None = None
    previous_hash: str | None = None
    evidence_hash: str | None = None

    def unsigned_dict(self) -> dict[str, Any]:
        return {
            "evidence_id": self.evidence_id,
            "event_type": self.event_type,
            "actor": self.actor,
            "actor_type": self.actor_type,
            "timestamp": self.timestamp.isoformat(),
            "correlation_id": self.correlation_id,
            "source_component": self.source_component,
            "action": self.action,
            "outcome": self.outcome,
            "approval_reference": self.approval_reference,
            "provenance": self.provenance,
            "previous_hash": self.previous_hash,
        }

    def to_dict(self) -> dict[str, Any]:
        payload = self.unsigned_dict()
        payload["evidence_hash"] = self.evidence_hash
        return payload


def digest_payload(payload: dict[str, Any]) -> str:
    """Return a deterministic SHA-256 digest over canonical JSON."""
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def chain_audit_evidence(events: tuple[AuditEvidence, ...]) -> tuple[AuditEvidence, ...]:
    """Attach previous/current hashes to evidence records."""
    chained: list[AuditEvidence] = []
    previous_hash: str | None = None
    for event in events:
        unsigned = AuditEvidence(
            evidence_id=event.evidence_id,
            event_type=event.event_type,
            actor=event.actor,
            actor_type=event.actor_type,
            timestamp=event.timestamp,
            correlation_id=event.correlation_id,
            source_component=event.source_component,
            action=event.action,
            outcome=event.outcome,
            approval_reference=event.approval_reference,
            provenance=event.provenance,
            previous_hash=previous_hash,
        )
        evidence_hash = digest_payload(unsigned.unsigned_dict())
        signed = AuditEvidence(
            **{
                **unsigned.unsigned_dict(),
                "timestamp": unsigned.timestamp,
                "evidence_hash": evidence_hash,
            }
        )
        chained.append(signed)
        previous_hash = evidence_hash
    return tuple(chained)


def verify_audit_chain(events: tuple[dict[str, Any], ...]) -> bool:
    """Verify the simple digest chain. This is not legal-grade immutability."""
    previous_hash: str | None = None
    for event in events:
        if event.get("previous_hash") != previous_hash:
            return False
        unsigned = {key: value for key, value in event.items() if key != "evidence_hash"}
        if digest_payload(unsigned) != event.get("evidence_hash"):
            return False
        previous_hash = str(event["evidence_hash"])
    return True


def build_reference_audit_evidence() -> tuple[AuditEvidence, ...]:
    """Build stable audit evidence over existing release controls."""
    now = datetime(2026, 1, 12, 15, 0, tzinfo=UTC)
    return chain_audit_evidence(
        (
            AuditEvidence(
                "AUD-REF-0001",
                "policy_evaluation",
                "governance.evidence",
                "system",
                now,
                "governance-release-correlation",
                "governance.policies",
                "evaluate repository policy checks",
                "passed",
                "Synthetic/reference audit event generated by governance.evidence.",
            ),
            AuditEvidence(
                "AUD-REF-0002",
                "access_attestation",
                "governance.evidence",
                "system",
                now,
                "governance-release-correlation",
                "governance.attestations",
                "generate reference access attestations",
                "approved_reference",
                "Synthetic/reference audit event generated by governance.evidence.",
                "ATT-AGENT-TOOLS-Q1",
            ),
            AuditEvidence(
                "AUD-REF-0003",
                "release_assurance",
                "release-owner",
                "role",
                now,
                "governance-release-correlation",
                "governance.release",
                "calculate release readiness",
                "reference_assurance_passed",
                "Synthetic/reference audit event generated by governance.evidence.",
                "REL-M8-REFERENCE",
            ),
        )
    )


__all__ = [
    "AuditEvidence",
    "build_reference_audit_evidence",
    "chain_audit_evidence",
    "digest_payload",
    "verify_audit_chain",
]
